

services:
  backend1:
    build: ./backend/chatapplication
    container_name: backend1
    ports:
      - "5001:5000"
    networks:
      - app_network

  backend2:
    build: ./backend/profiledata
    container_name: backend2
    ports:
      - "5002:5000"
    networks:
      - app_network

  backend3:
    build: ./backend/signup
    container_name: backend3
    ports:
      - "5003:5000"
    networks:
      - app_network

  backend4:
    build: ./backend/verify
    container_name: backend4
    ports:
      - "5004:5000"
    networks:
      - app_network

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend1
      - backend2
      - backend3
      - backend4
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
